// userPreferences
export const SET_PREFER_DARK_THEME = "SET_PREFER_DARK_THEME";

// ytapi
export const FETCH_PLAYLIST_DATA = "FETCH_PLAYLIST_DATA";
export const FETCH_PLAYLIST_DATA_SUCCESS = "FETCH_PLAYLIST_DATA_SUCCESS";
export const FETCH_PLAYLIST_DATA_FAILED = "FETCH_PLAYLIST_DATA_FAILED";
export const ADD_FETCHED_PLAYLIST_ID = "ADD_FETCHED_PLAYLIST_ID";
export const SET_PLAYLIST_URL = "SET_PLAYLIST_URL";
export const FETCH_VIDEO_DATA = "FETCH_VIDEO_DATA";
export const FETCH_VIDEO_DATA_SUCCESS = "FETCH_VIDEO_DATA_SUCCESS";
export const FETCH_VIDEO_DATA_FAILED = "FETCH_VIDEO_DATA_FAILED";
export const ADD_FETCHED_VIDEO_ID = "ADD_FETCHED_VIDEO_ID";
export const SET_VIDEO_URL = "SET_VIDEO_URL";

// ytplayer
export const SET_CURRENT_SONG_IDX = "SET_CURRENT_SONG_IDX";
export const SET_VIDEO_PLAYING = "SET_VIDEO_PLAYING";
export const TOGGLE_REPEAT = "TOGGLE_REPEAT";

// ytplaylist
export const ADD_PLAYLIST = "ADD_PLAYLIST";
export const REMOVE_PLAYLIST = "REMOVE_PLAYLIST";
export const RENAME_PLAYLIST = "RENAME_PLAYLIST";
export const SET_CHECKED_PLAYLISTS = "SET_CHECKED_PLAYLISTS";
export const ADD_PLAYING_PLAYLISTS = "ADD_PLAYING_PLAYLISTS";
export const ADD_VIDEO = "ADD_VIDEO";
export const REMOVE_VIDEO = "REMOVE_VIDEO";
export const DELETE_VIDEO = "DELETE_VIDEO"; // aims to replace REMOVE_VIDEO in the future
export const SET_CHECKED_VIDEOS = "SET_CHECKED_VIDEOS";
export const ADD_PLAYING_VIDEOS = "ADD_PLAYING_VIDEOS";
export const REMOVE_PLAYING_VIDEOS = "REMOVE_PLAYING_VIDEOS";
export const TOGGLE_PLAYING_VIDEO = "TOGGLE_PLAYING_VIDEO";
export const ADD_LIST_TO_PLAY = "ADD_LIST_TO_PLAY";
export const UPDATE_LIST_TO_PLAY = "UPDATE_LIST_TO_PLAY"; // (mayb) replace ADD_LIST_TO_PLAY
export const APPEND_LIST_TO_PLAY = "APPEND_LIST_TO_PLAY";
export const CLEAR_LIST_TO_PLAY = "CLEAR_LIST_TO_PLAY";
export const REMOVE_PLAYLIST_FROM_PLAYING = "REMOVE_PLAYLIST_FROM_PLAYING";
export const REMOVE_VIDEO_FROM_PLAYING = "REMOVE_VIDEO_FROM_PLAYING";
