// userPreferences
const SET_PREFER_DARK_THEME = "SET_PREFER_DARK_THEME";

// ytapi
const SET_PLAYLIST_URL = "SET_PLAYLIST_URL";
const FETCH_PLAYLIST_DATA = "FETCH_PLAYLIST_DATA";
const ADD_FETCHED_ITEM_ID = "ADD_FETCHED_ITEM_ID";
const SET_VIDEO_URL = "SET_VIDEO_URL";
const FETCH_VIDEO_DATA = "FETCH_VIDEO_DATA";
const ADD_FETCHED_VIDEO_ID = "ADD_FETCHED_VIDEO_ID";

// ytplayer
const SET_CURRENT_SONG_IDX = "SET_CURRENT_SONG_IDX";
const SET_VIDEO_PLAYING = "SET_VIDEO_PLAYING";

// ytplaylist
const SET_LOADED_FROM_DB = "SET_LOADED_FROM_DB";
const ADD_PLAYLIST = "ADD_PLAYLIST";
const REMOVE_PLAYLIST = "REMOVE_PLAYLIST";
const RENAME_PLAYLIST = "RENAME_PLAYLIST";
const SET_CHECKED_PLAYLISTS = "SET_CHECKED_PLAYLISTS";
const ADD_PLAYING_PLAYLISTS = "ADD_PLAYING_PLAYLISTS";
const ADD_VIDEO = "ADD_VIDEO";
const REMOVE_VIDEO = "REMOVE_VIDEO";
const RENAME_VIDEO = "RENAME_VIDEO";
const SET_CHECKED_VIDEOS = "SET_CHECKED_VIDEOS";
const ADD_PLAYING_VIDEOS = "ADD_PLAYING_VIDEOS";
const ADD_LIST_TO_PLAY = "ADD_LIST_TO_PLAY";
const CLEAR_LIST_TO_PLAY = "CLEAR_LIST_TO_PLAY";
const SHUFFLE_PLAYLIST = "SHUFFLE_PLAYLIST";

export {
  SET_PREFER_DARK_THEME,
  SET_PLAYLIST_URL,
  FETCH_PLAYLIST_DATA,
  ADD_FETCHED_ITEM_ID,
  SET_VIDEO_URL,
  FETCH_VIDEO_DATA,
  ADD_FETCHED_VIDEO_ID,
  SET_CURRENT_SONG_IDX,
  SET_VIDEO_PLAYING,
  ADD_PLAYLIST,
  REMOVE_PLAYLIST,
  RENAME_PLAYLIST,
  SET_CHECKED_PLAYLISTS,
  SET_LOADED_FROM_DB,
  ADD_LIST_TO_PLAY,
  ADD_PLAYING_PLAYLISTS,
  ADD_VIDEO,
  REMOVE_VIDEO,
  RENAME_VIDEO,
  SET_CHECKED_VIDEOS,
  ADD_PLAYING_VIDEOS,
  CLEAR_LIST_TO_PLAY,
  SHUFFLE_PLAYLIST,
};
