// ytapi
const SET_PLAYLIST_ID = "SET_PLAYLIST_ID";
const FETCH_PLAYLIST_DATA = "FETCH_PLAYLIST_DATA";

// ytplayer
const TOGGLE_YT_PLAYING = "TOGGLE_YT_PLAYING";

// ytplaylist
const ADD_PLAYLIST = "ADD_PLAYLIST";
const SHUFFLE_PLAYLIST = "SHUFFLE_PLAYLIST";

export {
  SET_PLAYLIST_ID,
  FETCH_PLAYLIST_DATA,
  TOGGLE_YT_PLAYING,
  ADD_PLAYLIST,
  SHUFFLE_PLAYLIST
};
