language: node_js
node_js:
  - "10.12.0"
  - "10.16.3"
warnings_are_errors: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
  - yarn test
  - CI=false yarn build
deploy:
  provider: surge
  project: ./build/
  domain: https://shuffler.surge.sh
  skip_cleanup: true
  on:
    branch: master
    node_js: "10.16.3"
branches:
  only:
    - master
