language: node_js
node_js:
  - "stable"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
  - yarn test
  - yarn build
deploy:
  provider: surge
  project: ./build/
  domain: ytrandomizer.surge.sh
  skip_cleanup: true
on:
  branch: master
